#!/bin/sh

# this is just an example!
# add your autostart stuffs here
redshift &
picom &
xrandr --output DP1 --auto --right-of LVDS1 &
xbacklight -set 100 &
pamixer -u &
xmodmap ~/.config/.Xmodmap
xrdb merge ~/.config/.Xresources &
feh --bg-fill ~/Pictures/wallpaper/wall.png &
xset r rate 200 50 &
# run bar script and dwm ( do not remove this )
bash ~/.config/chadwm/scripts/./bar.sh &
dwm
